version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique

  - name: playing_with_tests
    description: "Asignment 2"
    columns:
      - name: c_custkey
        description: "c_custkey from this table"
        tests:
          - unique
          - not_null
      - name: c_mktsegment
        tests:
          - accepted_values:
              values:
                [
                  "BUILDING",
                  "AUTOMOBILE",
                  "MACHINERY",
                  "HOUSEHOLD",
                  "FURNITURE",
                ]

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('my_first_dbt_model')
              field: id
  - name: snowflake_customer_purchases
    description: "The total purchases for each customer in snowflake sample data"
    columns:
      - name: c_custkey
        test:
          - unique
          - not_null
  - name: incremental_time
  - name: dates
    description: "incremental stuff"
  - name: cumulative_orders_by_date
    description: "The goal of the query is to get the cumulative sales for the order date."
    columns:
      - name: o_orderdate
        test:
          - unique
          - not_null
